name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: your-project-name
          entrypoint: src/main.ts
